// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241122055437_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Domain.Detection", b =>
                {
                    b.Property<int>("DetectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetectionId"));

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<int>("IntervalId")
                        .HasColumnType("integer");

                    b.Property<float>("PositionX")
                        .HasColumnType("real");

                    b.Property<float>("PositionY")
                        .HasColumnType("real");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("DetectionId");

                    b.HasIndex("IntervalId");

                    b.ToTable("Detections");
                });

            modelBuilder.Entity("Models.Domain.Interval", b =>
                {
                    b.Property<int>("IntervalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntervalId"));

                    b.Property<float>("AveragePersons")
                        .HasColumnType("real");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxPersons")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VideoId")
                        .HasColumnType("integer");

                    b.HasKey("IntervalId");

                    b.HasIndex("VideoId");

                    b.ToTable("Intervals");
                });

            modelBuilder.Entity("Models.Domain.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("IntervalId")
                        .HasColumnType("integer");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LogTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VideoId")
                        .HasColumnType("integer");

                    b.HasKey("LogId");

                    b.HasIndex("IntervalId");

                    b.HasIndex("VideoId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Models.Domain.Video", b =>
                {
                    b.Property<int>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VideoId"));

                    b.Property<int>("DurationInSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VideoId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("Models.Domain.Detection", b =>
                {
                    b.HasOne("Models.Domain.Interval", "Interval")
                        .WithMany("Detections")
                        .HasForeignKey("IntervalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interval");
                });

            modelBuilder.Entity("Models.Domain.Interval", b =>
                {
                    b.HasOne("Models.Domain.Video", "Video")
                        .WithMany("Intervals")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Models.Domain.Log", b =>
                {
                    b.HasOne("Models.Domain.Interval", "Interval")
                        .WithMany("Logs")
                        .HasForeignKey("IntervalId");

                    b.HasOne("Models.Domain.Video", "Video")
                        .WithMany("Logs")
                        .HasForeignKey("VideoId");

                    b.Navigation("Interval");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Models.Domain.Interval", b =>
                {
                    b.Navigation("Detections");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("Models.Domain.Video", b =>
                {
                    b.Navigation("Intervals");

                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
